### ISSUE TITLE
The concept of Recommender Systems

### ISSUE THREAD

**Issue by ankushtale** [PyDataPune/Talks#1]
Hello,
Ankush here. I am a Data Developer in CTO office at Barclays. I have been studying ML since more than an year now and have implemented a few things at work.

Recommender Systems is one of the applications of ML that touches our lives every single day. I recently gave a talk on it in my company which was very well received. I think, Recommender engines stand as a great introductory topic for newbies to not only wonder about applications of ML but also bust some myths and understand rationale behind an algorithm.

Wish to deliver a concise version of it at a PyData Meetup.
The presentation can be found on my GitHub.

**Comment by PyDataPune** [comment]
Confirming your talk for 9th meetup @Nov 25

**Comment by PyDataPune** [comment]
Need the link of the repository where all code and material is posted

**Comment by PyDataPune** [comment]
link of talk recording https://www.youtube.com/watch?v=AYQlREpZrrc&t=484s
