### ISSUE TITLE
Regression Analysis and the curious Marvel Movies Case

### ISSUE THREAD

**Issue by sigmakappa** [PyDataPune/Talks#10]
There have been multiple papers published earlier attempting to predict movie earnings based on different contributing factors like demography, time of year, casting, etc by using different data science models. 

This idea attempts implementing Regression techniques (Linear and Multiple Linear) in predicting Box Office earnings of MCU movies based on different associated and quantifiable factors.

**Comment by shreyas-kalmegh** [comment]
Hi, let us know the time duration required for the talk and your availability on 9th march.

**Comment by sigmakappa** [comment]
Time duration is 30 minutes and yes available on March 9.

**Comment by mayankskb** [comment]
Accepted for March 09 2019

**Comment by PyDataPune** [comment]
Once you uploaded your ppt somewhere please send the link here.
Thanks
