### ISSUE TITLE
Learning context through MultiPath CNN

### ISSUE THREAD

**Issue by prakharverma** [PyDataPune/Talks#11]
This presentation explains how at TomTom we improved accuracy in semantic segmentation by exposing higher contextual information. And how we used MultiPath CNN to harness the exposed contextual information.

**Comment by mayankskb** [comment]
Hi Prakhar,

Thanks for making issue. Accepted for Feb 09, 2019.

Regards,
Mayank Mishra

**Comment by sigmakappa** [comment]
Also request you to install a screen recorder (if that has voice recording also that's an advantage) over the machine that you would be using during the talk. Please respond/confirm ASAP you get this either to your point of contact @ PyData or here.

**Comment by prakharverma** [comment]
@sigmakappa OK! I will do so.

**Comment by prakharverma** [comment]
@sigmakappa I had a small query. Do you do a video recording of the sessions too or it's the only screen recording?

**Comment by mayankskb** [comment]
Hi,

We are planning to do video recording of the session to make it available at official youtube channel of pydata pune.

Thanks
Mayank Mishra

**Comment by mayankskb** [comment]
Well Prakhar, Can you give me write-up about the speaker for introducing him. You can give it to me here or send on the following email "pydata.pune@gmail.com"

**Comment by mayankskb** [comment]
Hey,

If possible can we get the link of ppt that you guys used for reference purpose.

Thanks
