### ISSUE TITLE
Sentiment analysis using NLTK

### ISSUE THREAD

**Issue by shoaib04** [PyDataPune/Talks#12]
Brief about use cases of NLTK and demo of Twitter sentiment analysis using NLTK.

I would like to deliver it as a lightning talk, I am fine if I get 20 minutes of time for presentation.

I will carry my own laptop and need a projector to show code samples

**Comment by shoaib04** [comment]
Hi, any update? 
So that I can align my schedule.

**Comment by Devendrabhat** [comment]
Hi @shoaib04, thanks for showing your interest.
Your talk is been accepted for upcoming PyData meetup on 14th of April.
Can you please give us a brief write-up about you for introducing you also please mention your laptop operating system so we can do screen recording your talk.

Also, I had a query that is are you going to show demo on live twitter data or are you going to use pre-downloaded twitter data?

**Comment by mohdshoaib04** [comment]
Hi,

Myself Mohd. Shoaib, python developer with interest in data analytics, have
2+ years of experience, currently working at pragmatic techsoft pvt Ltd.

Operating system is ubuntu

I will show demo with downloaded data from twitter api.

Thanks.

**Comment by Devendrabhat** [comment]
@sigmakappa Can you please guide him through the tool which he need to have on ubuntu based system for screen recording.

**Comment by mayankskb** [comment]
Thanks @shoaib04 for giving the talk. Closing the issue
