### ISSUE TITLE
Introduction to R language and handling astronomical datasets

### ISSUE THREAD

**Issue by Disha-Patil** [PyDataPune/Talks#13]
An introduction to R language and statistics with R will be covered. This will include introduction to the data visualisation with R. 
I will walkthrough a real life case study from astronomy domain explaining each stage of data analysis and how to do it in R. 

This talk will be 1 to 1.15 hr long.

**Comment by mayankskb** [comment]
Finalized for April 14

**Comment by Disha-Patil** [comment]
Wonderful. I will mark my calendar.

**Comment by mayankskb** [comment]
Also please share a brief write-up about you for introducing

**Comment by mayankskb** [comment]
@sigmakappa brother do share the name and information about the screen recording software.

**Comment by Disha-Patil** [comment]
About me:

I am computational engineer by training. Currently working on Industrial
Internet of Things. Somedays I am solving PDEs, somedays I am building a
machine learning model. I primarily work with R language.

Apart from work I am busy being an enthusiastic audience to theatre plays,
movies, and music concerts in the town. I am an amateur Ebru artist and
love to write.

-disha

**Comment by mayankskb** [comment]
Thanks Disha 


@sigmakappa  kindly add details related to screen recording software

**Comment by sigmakappa** [comment]
Hi here. Apologies for being a bit late in replying in suggesting a screen video recorder. Please go through the following readme to get an available screen recorder for your OS:

https://github.com/sigmakappa/ScreenRecorders

Let me know if a screen recorder for your OS is not available here.

**Comment by mayankskb** [comment]
Thanks for giving such wonderful talk.

**Comment by Disha-Patil** [comment]
It was very nice experience. Thank you for having me.

Hoping to stay in touch with the community :)
