### ISSUE TITLE
 Probability Distributions - What They Are And How Scientists Use Them?

### ISSUE THREAD

**Issue by vkaustubh** [PyDataPune/Talks#14]
The speaker will begin with what random variables are and how probability distributions are needed and used to describe their behavior. The speaker will give some examples of probability distributions and then proceed to talk about one of the older yet often not intuitively grasped distribution known as the chi-square distribution. The speaker will especially bring out how this distribution comes out naturally in the process of data modeling. The speaker will then conclude with some remarks on what probability distributions mean in the context of Machine Learning problems.

**Comment by mayankskb** [comment]
Thanks Kaustubh for making an issue.

Talk is accepted for April 14, 2019. Also please give us a brief write-up about you for introducing you.

@sigmakappa Please write the information related to which software he need to install on hi system for screen recording

**Comment by vkaustubh** [comment]
@mayankskb 
Here is a brief bio

> I am a PhD in Astrophysics from the Inter University Centre for Astronomy and Astrophysics aka IUCAA. I also have a keen interest in applications of information technology in astronomical research. I'm currently a Data Scientist under a national project hosted at IUCAA. And my interests include management and construction of astronomical databases, web applications and services, and applications of machine learning to astronomical problems. I am especially interested in helping astronomers tackle big data management challenges.

**Comment by vkaustubh** [comment]
@mayankskb @sigmakappa 

I had a discussion with @kaniruddha and we discussed the feasibility of me giving a board talk. As I understand this is feasible and hence I am giving a free style board talk.

**Comment by mayankskb** [comment]
cool this is awesome. In that case we will not have any ppt and demo then screen recording will not be required. Lets us know if you are planning to have some computer projector based things else we are good to go with board thing.

Thanks

**Comment by vkaustubh** [comment]
I can show some plots on the screen since drawing them is rather painful. Will that be troublesome?

**Comment by mayankskb** [comment]
nope not a problem

**Comment by vkaustubh** [comment]
Cool then! Dominantly board talk with the occasional plot on the screen.

**Comment by sigmakappa** [comment]
Hi here. Apologies for being a bit late in replying in suggesting a screen video recorder. Please go through the following readme to get an available screen recorder for your OS:

https://github.com/sigmakappa/ScreenRecorders

Let me know if a screen recorder for your OS is not available here.

**Comment by mayankskb** [comment]
Thanks for giving such wonderful and resourceful talk.
