### ISSUE TITLE
Dockerize your Dev environment with DOCKERFILE scripting.

### ISSUE THREAD

**Issue by Devendrabhat** [PyDataPune/Talks#16]

**Comment by Devendrabhat** [comment]
@sigmakappa please guide me with video recording on my Ubuntu system.

**Comment by sigmakappa** [comment]
Sure @Devendrabhat . Let me figure out the best screen recorder for Ubuntu. Currently I have a good open source option for Windows only.

**Comment by sigmakappa** [comment]
Hi here. Apologies for being a bit late in replying in suggesting a screen video recorder. Please go through the following readme to get an available screen recorder for your OS:

https://github.com/sigmakappa/ScreenRecorders

Let me know if a screen recorder for your OS is not available here.

**Comment by mayankskb** [comment]
We need to reschedule your talk @Devendrabhat. Presenting my apologies for canceling it the last moment.

Thanks

**Comment by PyDataPune** [comment]
Finalised and accepted for June 22, 2019
