### ISSUE TITLE
Introduction to Streaming Analytics

### ISSUE THREAD

**Issue by akhilcalsoft** [PyDataPune/Talks#18]
**Streaming Analytics:**

- Introduction to  data stream and unbounded data.
- Difference between stream and batching processing.
- IOT use cases for stream processing.
- Demo of IOT device data stream processing using Apache kafka and Apache Spark structured streaming.

**Talk Duration**: ~30 mins

**Comment by mayankskb** [comment]
Hey there. Apologies for being a bit late in replying in suggesting a screen video recorder. Please go through the following readme to get an available screen recorder for your OS:

https://github.com/sigmakappa/ScreenRecorders

Let me know if a screen recorder for your OS is not available here.

**Comment by mayankskb** [comment]
Kindly install this screen recorder on the machine which you will use for giving presentation and demo. We will need screen recording for making video to upload that on PyData Official youtube channel.
