### ISSUE TITLE
Election related data analysis

### ISSUE THREAD

**Issue by rigvedshenai** [PyDataPune/Talks#19]
A brief overview of all the election related data available from various sources.
Run-through of a project of putting various data sets together and visualizing trends.
What would next step of elections analysis would look like?
How social media or news media can be used to get the trends.
Possible misuse and theft of data. #lightningtalkproposal

**Comment by mayankskb** [comment]
Hey @rigvedshenai,

Rigved, It is a request, Can you convert your lighning talk in full time talk making it for 45 mins??

Thanks
Mayank Mishra

**Comment by rigvedshenai** [comment]
Sure. Would be happy to.

**Comment by sigmakappa** [comment]
Hey @mayankskb thanks for the extension request.

Hi @rigvedshenai thanks for the proposal. Would love to hear more about this idea and its contents. Would love to have a word with you soon. Ping me at 9756766726 (Whatsapp/messages) and lets arrange a time for a quick 5 minute call on this.  Looking forward for your call...

**Comment by PyDataPune** [comment]
[Outline For talk on Election Analysis.pptx](https://github.com/PyDataPune/Talks/files/3134117/Outline.For.talk.on.Election.Analysis.pptx)

Provided by Rigved

**Comment by rigvedshenai** [comment]
Hi @mayankskb @sigmakappa and team,
Would like to give a demo talk this saturday evening over Hangouts.
let me know the time and mode convenient to you guys,

**Comment by rigvedshenai** [comment]
I am putting in all the relevant links and references for the talk here.
https://docs.google.com/document/d/19Kq49etN3m5Da79kjYIFJPjBD6wRZDZhghpoujSfqas/edit?usp=sharing

Will keep on updating this.

**Comment by sigmakappa** [comment]
Hi there Rigved.


Yeah this should have been done during this weekend only. But since I'm out
and would be back on Monday night, I request you to reschedule this for the
next week somewhere on Tuesday or after at night.


Thanks!

**Comment by rigvedshenai** [comment]
I am setting up the demo talk via hangouts on 21st May - 9PM
Please ping me your gmail addresses at rigved12shenai@gmail.com and I will invite you via hangout.
Thanks.

**Comment by sigmakappa** [comment]
It's shagunprakash19@gmail.com here.

*Rest please do the needful.*

Thanks!!

**Comment by sigmakappa** [comment]
@rigvedshenai your talk is on the list.

CONFIRMED for June 22, 2019.

**Comment by PyDataPune** [comment]
Hi here. Apologies for being a bit late in replying in suggesting a screen video recorder. Please go through the following readme to get an available screen recorder for your OS:

https://github.com/sigmakappa/ScreenRecorders

Let me know if a screen recorder for your OS is not available here.
