### ISSUE TITLE
Machine Learning Deployment

### ISSUE THREAD

**Issue by shubhamjante** [PyDataPune/Talks#23]
Will demonstrate how to deploy machine learning model? Various architectures and hands on deployment

**Comment by mayankskb** [comment]
Hey,

Thanks for making a talk proposal. The idea is interesting. Please let us know the flow of talk, outlining and what concepts and probable methods you will be covering.

Thanks
Mayank Mishra

**Comment by shubhamjante** [comment]
Hi Team,
We always talk about Machine Learning Models and its performance on available data. In order to get benefit and provide services to other people who don't know ML we've to deploy our ML model. However, in production environment there are lot of data that may change over the short period of time.
I'll be covering following points:
- Traditional Software Development vs Machine Learning Process
- Machine Learning Pipeline
- Static vs Dynamic Training and Prediction
- Various ML Production System Architecture
- Production on Local/Cloud System
- Technology Stack
etc.

Thanks,
Shubham Jante

**Comment by mayankskb** [comment]
By any chance, planning to show live deployment or will just be talking about how to deploy only??

**Comment by shubhamjante** [comment]
There will be a live demo on deployment.

**Comment by shubhamjante** [comment]
Hi @mayankskb 
If you need any additional information please let me know. I'll be happy to share additional information.
Thanks.

**Comment by cooldeepVP** [comment]
Hi @mayankskb ,
Shubham is ready with his talk can you prioritise his talk : )

**Comment by mayankskb** [comment]
Hey Shubham,

Can we have your talk this month? Please let me know about it.

Thanks
Mayank Mishra

**Comment by shubhamjante** [comment]
> Hey Shubham,
> 
> Can we have your talk this month? Please let me know about it.
> 
> Thanks
> Mayank Mishra


Hi Mayank,
Sure, we can talk about it.

Thanks,
Shubham Jante

**Comment by mayankskb** [comment]
Thanks, Shubham! So, please share your line up for the event.

**Comment by shubhamjante** [comment]
@mayankskb 
Sure Mayank will send it to you. Do you want me to email the details or post here?

**Comment by mayankskb** [comment]
please post them here

**Comment by shubhamjante** [comment]
@mayankskb 

I'll be covering following points:

- Traditional Software Development vs Machine Learning Process
- Machine Learning Pipeline
- General Guidelines to Data Scientists to design predictive pipeline
- DevOps for Machine Learning
- Agile way for Machine Learning Projects
- Static vs Dynamic Training and Prediction
- Various ML Production System Architecture
- Production Systems
- Technology Stack

**Comment by mayankskb** [comment]
Hey Shubham,

Please confirm your availability for Oct 5.

Thanks
Mayank Mishra

**Comment by shubhamjante** [comment]
Hi @mayankskb,

I'm available on 5th Oct.
Could you please let me know the agenda? So that i'll start my preparations.

**Comment by mayankskb** [comment]
Agenda, as in??

**Comment by shubhamjante** [comment]
Like, what we'll be doing on 5th Oct.? Is it a meeting to discuss about my ideas and plan or is it something else?

**Comment by mayankskb** [comment]
This is a talk based meetup, where-in we have speakers and audience. Speakers will present their content through demo/whiteboarding, slides. 

Just like a mini-conference.

For reference please go through this https://www.youtube.com/channel/UCEnagt088yX-ruTalg-GJeQ

Thanks 
Mayank Mishra

**Comment by mayankskb** [comment]
Confirming your talk for Oct 05.

**Comment by mayankskb** [comment]
Hey,

We will be recording your session. So if you have slides/demo/paper. Kindly keep it handy.

Also, you need to install screen recording software which can capture the presentation on your laptop.

If you have any other alternate go with that if not then please go through the following readme to get an available screen recorder for your OS:

https://github.com/sigmakappa/ScreenRecorders

Let me know if a screen recorder for your OS is not available here.

Also, after installing do testing of it that it is working properly or not.

Also, please give confirmation, once done with screen recorder testing stuff.

Thanks
Mayank Mishra

**Comment by mayankskb** [comment]
Also, please share a brief writeup about you that we will be using for introducing you.

Thanks

**Comment by cooldeepVP** [comment]
Thanks Mayank,
Goodluck Shubham !

**Comment by shubhamjante** [comment]
Hi @mayankskb,

I just wanted to confirm the time limit for my talk? How many people will attend the meetup, if you have any general idea that would be great?

Yes, I have screen recording software. Will be able to share the screen video after the talk.

About me:
Shubham is passionate about Machine learning and it's engineering aspects of it. While working at e-Zest solutions as Machine learning Engineer, he was instrumental in designing ML pipelines that simplify work. He has extensive experience in almost all aspects of ML pipeline including deployment.  & take initiatives in enriching Data Science community with his experience.

Please let me know if you need any additional information.

Thanks,
Shubham Jante

**Comment by shubhamjante** [comment]
> Thanks Mayank,
> Goodluck Shubham !

Thank you @cooldeepVP.

**Comment by mayankskb** [comment]
Hi,

About the length of talk at max 1 hr and 5-10 mins for Q n A.
About the audience: Till now what we have seen is on average foot-fall of 40-60 people.

Thanks,
Mayank Mishra

**Comment by shubhamjante** [comment]
Thank you, Mayank

**Comment by mayankskb** [comment]
Hi Shubham,

Please fill this form: https://forms.gle/h784Vv3cd2D6HY4M9

Thanks 
Mayank Mishra

**Comment by shubhamjante** [comment]
Done

**Comment by mayankskb** [comment]
Hi Shubham,

Please install the screen recording software mentioned above. or if you have any that would also work, but make sure that it should not leave water mark on the video

Thanks
Mayank Mishra

**Comment by shubhamjante** [comment]
Hi Mayank,
I've installed it. No, it will not include watermark.

**Comment by mayankskb** [comment]
Cool!! See you on Oct 05, 2019

**Comment by mayankskb** [comment]
Hi Shubham,

Kindly Upload your screen recording to this folder. 
Link: https://drive.google.com/drive/folders/1NvszNmVAP-T5QwLH4yuBpQJWIfHudBm7?usp=sharing

Let me know if you do not have access to this folder.


Thanks
Mayank Mishra

**Comment by shubhamjante** [comment]
Done

**Comment by mayankskb** [comment]
Thanks, Shubham. Loved your talk at PyData Pune. I would love to hear more in the future. Feel free to make issues in the future. 

Thanks
Mayank Mishra
