### ISSUE TITLE
[Talk Proposal] A 'Hello World' for Quantum Annealing

### ISSUE THREAD

**Issue by subwayHareArmy** [PyDataPune/Talks#24]
Hello, I'm Ayush.
I wanted to propose a Lightning Talk for the next meetup. Here are the details.

===========
Short Summary -

The hype and mystery surrounding Quantum Computing can make it seem like a daunting field to get into, especially for outsiders.
My talk hopes to deliver some insight into the field by presenting a 'Hello World' code for Adiabatic Quantum Computing, a subfield of Quantum Computing. The presented code will aim to solve Sudoku using D-Wave's quantum computing libraries in Python and provide an introduction for the same.

============

I look forward to hearing from you regarding the talk. Thank you.
(I'll be In Pune till ~ 28th July)

**Comment by mayankskb** [comment]
Hey,

Thanks for making an issue. We would like to have your talk for our July edition. Setting things for July 27, 2019. Will give u final dates only after receiving confirmation. 

From our side, talk is confirmed.

Thanks
Mayank Mishra

**Comment by subwayHareArmy** [comment]
Hello. 

Thanks for the confirming it from your end. There's a bit of work still remaining, but I'm okay with having it on the 27th of July since I'll be leaving on the 28th/29th.
Consider this my confirmation.

Ayush

**Comment by mayankskb** [comment]
Hey,

We will be recording your session. So if you have slides/demo/paper. Kindly keep it handy.

Also, you need to install screen recording software which can capture the presentation on your laptop.

If you have any other alternate go with that if not then please go through the following readme to get an available screen recorder for your OS:

https://github.com/sigmakappa/ScreenRecorders

Let me know if a screen recorder for your OS is not available here.

Also, after installing do testing of it that it is working properly or not. 

Thanks 
Mayank Mishra

**Comment by mayankskb** [comment]
Hey Ayush,

Please send us a small writeup about you.

Thanks 
Mayank Mishra

**Comment by PyDataPune** [comment]
Hey Ayush,
Please send a small writeup about you for introducing you and also help us with your contact details.
Thanks

**Comment by subwayHareArmy** [comment]
Hello.

Sorry for the late reply.

I'm downloading ShareX mentioned in the repository you'd linked for Screen
Recording since I use Windows. I'll let you know if I face any problems in
doing so.
As for my personal contact details:

*Name:* Ayush Yembarwar

*Mobile Number:* +91-7690023451

*Email Address:* ayushyembarwar@gmail.com *or*
f2016657@pilani.bits-pilani.ac.in

*About Me:* Ayush Yembarwar is an undergraduate student at BITS Pilani,
studying for dual degrees in Physics and Electronics. An AI enthusiast,
he's also interested in new technologies like Quantum Computing. He likes
listening to music, reading and telling everybody how cool Liverpool is.


Regards,
Ayush Yembarwar

**Comment by subwayHareArmy** [comment]
Hello.

Sorry for the late reply.

I'm downloading ShareX mentioned in the repository you'd linked for Screen
Recording since I use Windows. I'll let you know if I face any problems in
doing so.
As for my personal contact details:

*Name:* Ayush Yembarwar

*Mobile Number:* +91-7690023451

*Email Address:* ayushyembarwar@gmail.com *or*
f2016657@pilani.bits-pilani.ac.in

*About Me:* Ayush Yembarwar is an undergraduate student at BITS Pilani,
studying for dual degrees in Physics and Electronics. An AI enthusiast,
he's also interested in new technologies like Quantum Computing. He likes
listening to music, reading and telling everybody how cool Liverpool is.


Regards,
Ayush Yembarwar

**Comment by mayankskb** [comment]
Hey Ayush,

Kindly upload the screen recording here: https://drive.google.com/drive/folders/1_az_VJ5sNWfKFdtcRqCfBnucrC_MVmBR?usp=sharing

Let me know in case of any issue related to access the folder.

Thanks
Mayank Mishra

**Comment by subwayHareArmy** [comment]
I'm not facing any issues, uploading it right now.

**Comment by mayankskb** [comment]
cool!! Do let me know once done

**Comment by subwayHareArmy** [comment]
It's done uploading, it's an mp4 file.

**Comment by mayankskb** [comment]
Yes!! Thanks, buddy will process the talk as soon as possible and will send you the link after uploading on youtube.

For now, closing the issue. feel free to propose new talks as and when you come to Pune. Would love to conduct a full time talk this time

**Comment by subwayHareArmy** [comment]
Thanks, I'll definitely take you up on that opportunity!

**Comment by mayankskb** [comment]
yo meanwhile stay connected with us on Telegram or on whatsapp : 8380810361
