### ISSUE TITLE
Time Series Forecasting with FbProphet and Comparison with Other Algorithms

### ISSUE THREAD

**Issue by sonarsushant** [PyDataPune/Talks#27]
**Title:**
Time-series Forecasting using FBProphet

**Description:**
In this session, I will talk about analysis of time-series data and training a model to forecast it. I will discuss how trend, seasonality as well as special events like festivals, promotion days make impact on time-series data and can be used to train model. I will discuss Facebook's 'fbprophet' library and its comparison with traditional algorithms like ARIMA, SARIMAX. Also, how fbprophet can be used with other machine learning models like XGB.

**Prerequisites:**
Familiarity with python, pandas and matplotlib.

**Duration:**
This talk will go about an hour. We will analyze of real-life time-series data followed by training and comparing various models.

**Comment by mayankskb** [comment]
Hey,

We would like to have your talk for November Meetup. The probable date would be 16 Nov 2019. Do let me know your availability for the same.


Thanks
Mayank Mishra

**Comment by sonarsushant** [comment]
Hi Mayank,

We can have my talk on 16th Nov.
Please let me know the further procedure. 

Thanks,
Sushant

**Comment by mayankskb** [comment]
Hi,

Please do let me know once you are done with finalizing the content. I would like to have a look at it or best would be if you can write down the line-up and brief about it

Regards,
Mayank Mishra

**Comment by sonarsushant** [comment]
Hi Mayank,

Here is the line-up for talk. I will use power point presentation and jupyter notebooks for talk. Let me know any changes if required.

1.	Basic information about time-series data. How it is different from non-temporal data and what additional things to consider while forecasting it?
2.	Analysis of time-series data and time-series decomposition (Jupyter notebook).
3.	Traditional models to forecast time-series and issues with them.
4.	Using FbProphet to forecast time-series and its advantages (Jupyter Notebook) .
5.	Using FbProphet along with XGB (Ensmeble) to forecast time-series (Jupyter Notebook)

Thanks,
Sushant Sonar

**Comment by mayankskb** [comment]
Hi Sushant,

Please go ahead with the content preparation. Finalizing your talk for Nov 16, 2019. More details will be added shortly regarding instructions and other guidelines.

Thanks
Mayank Mishra

**Comment by mayankskb** [comment]
Hi,

We will be recording your session. So if you have slides/demo/paper. Kindly keep it handy.

Also, you need to install screen recording software which can capture the presentation on your laptop.

If you have any other alternate go with that if not then please go through the following readme to get an available screen recorder for your OS:

https://github.com/sigmakappa/ScreenRecorders

Let me know if a screen recorder for your OS is not available here. Also, after installing do testing of it that it is working properly or not. Also, please give confirmation, once done with screen recorder testing stuff.

Thanks
Mayank Mishra

**Comment by mayankskb** [comment]
Hi Shushant,

Do send me a small writeup about you. We will use that for introducing you. Also, please send me your contact details at pydata.pune@gmail.com. Don't worry we are not going to share them with anybody.

Thanks
Mayank Mishra

**Comment by sonarsushant** [comment]
Hi Mayank,

Screen recorder is working for me and I have mailed you a small writeup about me.

Thanks,
Sushant Sonar

**Comment by mayankskb** [comment]
Please upload your screen recording to this folder :

https://drive.google.com/drive/folders/1isoGg2-qzFdGJyXxd7JKXasSiYoIhbAD?usp=sharing

Thanks
Mayank Mishra

**Comment by palash247** [comment]
Hi Sushant, thanks for sharing your knowledge. It would be great if you can share the notebook too.

**Comment by sonarsushant** [comment]
Hi,
Refer [this](https://github.com/sonarsushant/TimeSeriesForecasting) link for notebook.

**Comment by PyDataPune** [comment]
Hi Shushant,

Great having you on board for that meetup and thanks for uploading the screen recording. Closing this issue as the purpose of this issues is completed.

Feel free to make new proposals anytime.

Thanks
Mayank Mishra
