### ISSUE TITLE
Proposal for lightning talk on ipython widgets framework.

### ISSUE THREAD

**Issue by pushkarnimkar** [PyDataPune/Talks#29]
# Description
IPython widgets framework is created with the intention of bridging the gap between data practitioner and data. Eventhough it's a well known framework, I find it is worth to have an introductory talk about it.

# Prerequisite
Familiarity with python and jupyter lab/notebook.

# Scope
* Introduction to interact / quick-start [doc-link](https://ipywidgets.readthedocs.io/en/stable/examples/Using%20Interact.html).
* Understanding whats going on inside [doc-link](https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20Low%20Level.html) (please review if this is required).
* Quick overview of widgets list [doc-link](https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20List.html).
* Quick overview of container widgets [doc-link](https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20List.html#Container/Layout-widgets).
* Widgetized matplotlib [project-link](https://github.com/matplotlib/jupyter-matplotlib).
* Example use-case of studying misclassified samples of a classification model (suggestions for other use-cases are welcome).

**Comment by pushkarnimkar** [comment]
https://ipywebrtc.readthedocs.io/en/latest/api.html#ipywebrtc.webrtc.CameraStream

**Comment by PyDataPune** [comment]
Hi,

Good Proposal and let's finalize this talk soon.
Your inputs are required.

Thanks
Admin @ PyData Pune

**Comment by mayankskb** [comment]
Hi Pushkar,

We would like to schedule your talk for Feb meetup. Most probably on 22 Feb. Please let us know your availability regarding the same.

**Comment by pushkarnimkar** [comment]
Hi Mayank. We can schedule it for February.

**Comment by mayankskb** [comment]
Cool. In this case scheduling it for Feb 22, 2020.

**Comment by mayankskb** [comment]
Hi,

Please send a small write-up about you for introducing you.

We will be recording your session. So if you have slides/demo/paper. Kindly keep it handy.

Also, you need to install a screen recording software that can capture the presentation on your laptop.

If you have any other alternate go with that if not then please go through the following readme to get an available screen recorder for your OS: https://github.com/sigmakappa/ScreenRecorders

Let me know if a screen recorder for your OS is not available here. Also, after installing do testing of it that it is working properly or not. Also, please give confirmation, once done with screen recorder testing stuff.

Thanks
Mayank Mishra

**Comment by pushkarnimkar** [comment]
https://github.com/pushkarnimkar/ipywidgets-demo

**Comment by mayankskb** [comment]
Hi Pushkar,

Please find the face recording here: https://drive.google.com/drive/folders/1R0150lU2ZIXIb7O7KvUKl5gwWN7TXwq8?usp=sharing

Please do the screen recording in sync with the face recording and upload that in the same folder. 
Please do this as soon as possible (holi leaves)

Thanks
Mayank Mishra

**Comment by mayankskb** [comment]
Hi Pushkar,

Please send the screen recording. We need to process it and upload it as soon as possible.

Thanks
Mayank Mishra

**Comment by mayankskb** [comment]
Closing this issue as the talk has been delivered. Feel free to make a new talk proposal.

Thanks 
Mayank Mishra
