### ISSUE TITLE
Introduction to Topic Modelling

### ISSUE THREAD

**Issue by bitsbuffer** [PyDataPune/Talks#3]
Topic modelling is an unsupervised technique of extracting meaningful information from the text corpus.

**Why topic modelling ?**
The amount of text data that is being generated in the form of Whatsapp messages, Tweets, Facebook posts, reviews etc. need some mechanism to identify patterns, behaviors and trends. Finding what the text data is about and finding abstract themes in the data may render useful information.

In this session, I will cover frequently used algorithms to topic modelling with some use cases on publicly available data.
I will also introduce NLP basics such as Tokenization, Stemming, Lemmatization and Vectorization of the raw text.

**Outline of the talk**
    Introduction to topic modelling
    Latent Semantic Analysis
    Latent Dirichlet Allocation
    Topic Modelling using Deep learning - lda2vec
    Demos

**Comment by kaniruddha** [comment]
Hi, Could you tell me the estimated time you will need for the talk and the resources you need?

**Comment by bitsbuffer** [comment]
I will need at least an hour and half for talk.I would like to present a demo for that I would need projector, I will carry my own laptop for demo.

**Comment by shreyas-kalmegh** [comment]
Hi, let us know if your resources(notebooks/ code) are ready. If not how long will it take? Also, let us know of your availability so that we can confirm this talk. Feel free to ask or discuss anything if needed.

**Comment by bitsbuffer** [comment]
I have demos ready with me for Latent Semantic Analysis and Latent Dirichlet Allocation. The lda2vec part won't take much time. 
It will also need a day or two for preparing slides.

Regarding availability - I'll be available in entire February apart from (9, 10, 11, 12).

**Comment by shreyas-kalmegh** [comment]
Hi, we couldn't finalize your talk for the last meetup as it was on 10th feb. Let us know if you are available on 10th march.

**Comment by bitsbuffer** [comment]
I will be available on 10th March. We can finalize the meetup.

**Comment by shreyas-kalmegh** [comment]
Thanks for the confirmation.

**Comment by shreyas-kalmegh** [comment]
Talk finalized for March 10 event.

**Comment by mayankskb** [comment]
sir event date is changed from march 10 to march 09. let me have your confirmation for the same.

**Comment by bitsbuffer** [comment]
I don't have any problem.

**Comment by mayankskb** [comment]
Thanks!! Also please let me know the time frame that you may need to execute your talk.

**Comment by sigmakappa** [comment]
> I will need at least an hour and half for talk.I would like to present a demo for that I would need projector, I will carry my own laptop for demo.

@bitsbuffer would that be same time as of now?

FYI @mayankskb

**Comment by mayankskb** [comment]
Also please share a write-up to introduce you sir at following mail : pydata.pune@gmail.com

**Comment by bitsbuffer** [comment]
I will need 1.5 hrs for talk. We can keep half hour for open discussion (depends on organizers). I will try to show a demo within 1.5 hrs time frame. I will try to keep session focussed on intuition and light on mathematics. If someone is extremely interested in maths and implementation part, we can use extra half an hour time frame if organizers permit.

**Comment by sigmakappa** [comment]
Also request you to install a screen recorder (if that has voice recording also that's an advantage) over the machine that you would be using during the talk. Please respond/confirm ASAP you get this either to your point of contact @ PyData or here.

**Comment by PyDataPune** [comment]
Hi Shubhmay bro, Please help me with a write-up about you for introducing you.
Can email on "pydata.pune@gmail.com"

**Comment by PyDataPune** [comment]
Hey Shubhmay! Once you uploaded your presentation somewhere like Speakerdeck or slideshare. Please send the link of it here.

Thanks

**Comment by mayankskb** [comment]
Hey Shubhmay,

Please share link of your ppt  here so that I can close this issue.

Thanks

**Comment by prateekgupta891** [comment]
Shubhmay can you please share the link for your presentation here.

**Comment by bitsbuffer** [comment]
Please find the presentation link below:
https://www.slideshare.net/secret/fqVI1q9Hkb8TEN
