### ISSUE TITLE
Proposal for lightening talk: Transfer learning with pre-trained models 

### ISSUE THREAD

**Issue by suvarnak** [PyDataPune/Talks#30]
Training a deep neural network requires lot of labelled data, engineering (for choosing architecture and tuning hyper parameters) and of course, compute. If wish to reap the benefits for deep learning without the pain of training & tuning, pre-trained models can provide solution. This introductory talk can help in getting started with transfer learning.

### **Prerequisite**
Familiarity with Python, Machine Learning and Neural Networks

### **Scope**
Common steps to train a deep network
Transfer Learning with Pretrained Models
Repurposing a pretrained model for your own needs
Example usecase for image classification

**Comment by mayankskb** [comment]
Hey Suvarna,

Thanks for making an issue. Just FYI,  lightning talk will be of 15 mins max. You need to completed your talk with that period only.

Please give confirmation for the above info and your consent for the same.

Also, let me know about your availability for Oct 5.

Thanks
Mayank Mishra

**Comment by suvarnak** [comment]
Hello Mayank,

I am ok with 15 minutes talk. I  wont be able to have detailed code walkthrough for the usecase, but I can share the code for participants to explore later.
 I am available on Oct 5.

Regards

**Comment by mayankskb** [comment]
Thanks!! Scheduling your lightning talk for Oct 5, 2019.

Regards,
Mayank Mishra

**Comment by mayankskb** [comment]
Hey,

We will be recording your session. So if you have slides/demo/paper. Kindly keep it handy.

Also, you need to install screen recording software which can capture the presentation on your laptop.

If you have any other alternate go with that if not then please go through the following readme to get an available screen recorder for your OS:

https://github.com/sigmakappa/ScreenRecorders

Let me know if a screen recorder for your OS is not available here.

Also, after installing do testing of it that it is working properly or not.

Also, please give confirmation, once done with screen recorder testing stuff.

Thanks
Mayank Mishra

**Comment by suvarnak** [comment]
Thanks Mayank,
I just tested screen recording with ShareX and its working fine.
Regards
Suvarna

**Comment by mayankskb** [comment]
Hi,

Please send a small write-up about you. We will use it for introducing you.

Thanks
Mayank Mishra

**Comment by suvarnak** [comment]
Hello Mayank,

Just mailed you. Please check.

Regards

**Comment by mayankskb** [comment]
Hi,

Please fill this form: https://forms.gle/h784Vv3cd2D6HY4M9

Thanks 
Mayank Mishra

**Comment by suvarnak** [comment]
Filled. Thanks .

**Comment by mayankskb** [comment]
Thanks Suvarna for your kind support. See you on Oct 05, 2019

**Comment by suvarnak** [comment]
I've shared an item with you:

TransferLearning_Suvarna.mp4
https://drive.google.com/file/d/1Tuj5z4rAnei3LlEGwAcmHPS7vq17-wIc/view?usp=sharing&ts=5d999a02

It's not an attachment -- it's stored online. To open this item, just click  
the link above.

Hi,

This is screen recording of my talk on Transfer Learning

Best Regards

**Comment by suvarnak** [comment]
Hello Mayank,

PF the code and slides at https://github.com/suvarnak/TL_demo.git
I have also uploaded the video of screen recording of the talk in my google drive. 

Thanks & Best Regards
Suvarna

**Comment by mayankskb** [comment]
Hi Suvarna,

Kindly upload the screen recording to this folder.
Link: https://drive.google.com/drive/folders/1NvszNmVAP-T5QwLH4yuBpQJWIfHudBm7?usp=sharing

Let me know in case you do not have access to this folder.


Thanks
Mayank Mishra

**Comment by mayankskb** [comment]
Thanks, Suvarna. Loved your presence at PyData Pune event. Your talk was quite informative. Would love to hear more in the future from you. Feel free to make talk proposals in the future.


Closing this issue.
Thanks 
Mayank Mishra
