### ISSUE TITLE
Map Features Extraction Service

### ISSUE THREAD

**Issue by swapniludar** [PyDataPune/Talks#33]
TomTom has been working on map features (e.g. roads, building, water areas, etc.. ) extraction from satellite imagery using Convolutional Neural Network (CNN) and Image Processing. In order to make the extraction capability accessible to everyone within TomTom, we have created “Map features extraction service”. It exposes simple and intuitive APIs over HTTP/2 for inference on trained models.

**Comment by mayankskb** [comment]
Thanks Swapnil... Confirming talk for Oct 05, 2019.

**Comment by mayankskb** [comment]
Please send a brief writeup about you, which we will be using for introducing you. 

Thanks
Mayank Mishra

**Comment by swapniludar** [comment]
Hi Mayank, 

Ravi Panchani (@rvpanchani) from my team will be delivering a talk. 

Here is a write up about him:
A software professional and machine learning enthusiast building a strong foundation for safer, cleaner and congestion free world by automating and improving maps production processes at TomTom.

Thank you!

Regards
Swapnil

**Comment by mayankskb** [comment]
Thanks, Swapnil for the talk. Feel free to make a proposal for talk anytime. We would love to have your talk as well. Feel free to do so. 


Closing this issue. 

Thanks
Mayank Mishra
