### ISSUE TITLE
Time series forecasting

### ISSUE THREAD

**Issue by SaranjeetKaur** [PyDataPune/Talks#36]
Understanding what is a time series and it's characterization.

**Comment by mayankskb** [comment]
Hi Saranjeet,

I am sure you might be preparing the content for your talk. From our side consider this talk as accepted for Nov 16, 2019.

Please let us know what all you would need to deliver your talk in the best possible way.

More details about the event + guidelines will be shared soon.

Thanks
Mayank Mishra

**Comment by SaranjeetKaur** [comment]
Yup will keep you posted

**Comment by mayankskb** [comment]
Hi Saranjeet,

Please let me know the lineup of your talk. Kindly list them here. 

Thanks
Mayank Mishra

**Comment by mayankskb** [comment]
Hi,

We will be recording your session. So if you have slides/demo/paper. Kindly keep it handy.

Also, you need to install screen recording software which can capture the presentation on your laptop.

If you have any other alternate go with that if not then please go through the following readme to get an available screen recorder for your OS:

https://github.com/sigmakappa/ScreenRecorders

Let me know if a screen recorder for your OS is not available here. Also, after installing do testing of it that it is working properly or not. Also, please give confirmation, once done with screen recorder testing stuff.

Thanks
Mayank Mishra

**Comment by mayankskb** [comment]
Hi Saranjeet,

Do send me a small writeup about you. We will use that for introducing you. 

Thanks
Mayank Mishra

**Comment by SaranjeetKaur** [comment]
Line-up of my talk:
1. What can be forecast?
2. Graphing your data
3. The forecasting toolbox
4. What if no historical data is available?
5. Some more methods and models

The elaboration of point 5 will depend on the time availability and
interest of the audience

**Comment by SaranjeetKaur** [comment]
Also please change the talk title to "Time series forecasting"

**Comment by mayankskb** [comment]
Thanks Saranjeet for your inputs. One more thing please do the screen recording setup and let me know the status.

**Comment by SaranjeetKaur** [comment]
Exclude point 5 from the line-up

**Comment by PyDataPune** [comment]
Hi Saranjeet,

Thanks for delivering the talk. Closing this issue now. Please share the screen recording as soon as possible. 
Also, feel free to make new talk proposals.

Thanks
Admin @ PyData Pune

**Comment by SaranjeetKaur** [comment]
Dear Admin (PyData Pune),

I thank the Organizers at PyData Pune for giving me the opportunity for
presenting my talk.
Apologies for the delay in sharing the screen recording with you.
The screen recording is uploaded in the stated folder.

Cheers,
Saranjeet
