### ISSUE TITLE
Machine Learning Recipies for Time Series Forecasting

### ISSUE THREAD

**Issue by bitsbuffer** [PyDataPune/Talks#39]
Hi,

The gist of this lighting talk will be

1. How time series data is different than cross sectional data ? 
2. Feature engineering tricks to apply on time series data ?
3. Model assessment and cross validation.

**Comment by mayankskb** [comment]
Hi,

Please send a small write-up about you for introducing you.

We will be recording your session. So if you have slides/demo/paper. Kindly keep it handy.

Also, you need to install screen recording software which can capture the presentation on your laptop.

If you have any other alternate go with that if not then please go through the following readme to get an available screen recorder for your OS:

https://github.com/sigmakappa/ScreenRecorders

Let me know if a screen recorder for your OS is not available here. Also, after installing do testing of it that it is working properly or not. Also, please give confirmation, once done with screen recorder testing stuff.

Thanks
Mayank Mishra

**Comment by mayankskb** [comment]
Hi,

Feel free to make any new talk proposal. Closing this issue.

Thanks
Mayank Mishra
