### ISSUE TITLE
Intelligent Chatbot to Automate the Interview

### ISSUE THREAD

**Issue by thombrem** [PyDataPune/Talks#4]
Intelligent Chatbot to Automate the Interview

**Comment by mayankskb** [comment]
Hey Milind,

Thanks for making an issue. Can you add details like what you will be covering. Which all algorithms you will discuss.

Thanks

**Comment by thombrem** [comment]
Hi Mayank,

I will send out the outline, but lets not target tomorrow, This will take
time

Regards
Miilnd

**Comment by mayankskb** [comment]
Yeah!! Not planning for tomorrow. Feel free bro. We will ask you before scheduling it. :)

**Comment by mayankskb** [comment]
Hey Milind, 
Let me know when we can have your talk. Also please provide details about your talk.
Thanks 
Mayank

**Comment by thombrem** [comment]
yes, should update with details in next week

**Comment by mayankskb** [comment]
Hey Milind,

Let me know when we can have your talk. Also please provide details about your talk.

Thanks
Mayank

**Comment by thombrem** [comment]
Hey Mayank,

Lets pick a date in the last week of February (23/24) 2019 and then things
will have to happen! We should have a Talk followed by a Demo. I will give
you the outline one week before (16/17 Feb) so that you can take a call.
Please rest assured, people will feel educated as well as entertained!

Thanks for the follow up.

Regards
Milind Thombre
9823097126

**Comment by mayankskb** [comment]
This is good let us finalize the March Date and will give you a shout of it.

**Comment by mayankskb** [comment]
Hey Milind,

We are thinking to place your talk for March 10 event. Please let us know about your availability for the same.

Thanks
Mayank Mishra

**Comment by thombrem** [comment]
I'm here on March 10, I will mark my calendar once you confirm Mayankji

**Comment by mayankskb** [comment]
Confirmed Milind Sir G.

**Comment by mayankskb** [comment]
Sir event date is changed from march 10 to march 09. Let me have your confirmation for the same.

**Comment by mayankskb** [comment]
Also Please let me know the exact time frame that you need to execute your talk

**Comment by thombrem** [comment]
Gosh Mayank, 

I have been terribly busy with my startup, but a promise is a promise! I will deliver a talk on 9th March (Saturday) if the slot is still open! If not there is always a next time! 

Either ways, please let me know as soon as you see this, so that I can budget a day or two in the prep work this week itself to polish the talk and time it.

My apologies for not writing back earlier. 

Regards

Milind

**Comment by mayankskb** [comment]
Hey Milind,

I have already listed your talk for March 09 meetup. For replying late no probs. Milind I need a wrietup about you for introducing you on the day of event. 

Thanks
Mayank

**Comment by mayankskb** [comment]
Hey Milind,

I have already listed your talk for March 09 meetup. For replying late no probs. Milind I need a wrietup about you for introducing you on the day of event. 

Thanks
Mayank

**Comment by thombrem** [comment]
Hi Mayank, 
I will send you a writeup soon, my priority is getting the slidedeck in order
Regards
Milind

**Comment by sigmakappa** [comment]
Also request you to install a screen recorder (if that has voice recording also that's an advantage) over the machine that you would be using during the talk. Please respond/confirm ASAP you get this either to your point of contact @ PyData or here.

**Comment by thombrem** [comment]
Screen recorder? Not sure we need it, but do you recommend any? FOSS perhaps?

**Comment by thombrem** [comment]
ok installed gamebar, will test it in a bit....

**Comment by sigmakappa** [comment]
Good! Make sure this doesn't give any watermarks or impressions like that post recording.

**Comment by PyDataPune** [comment]
Please send the link of ppt and materials used here!! 

Thanks

**Comment by mayankskb** [comment]
Hey Milind,

Please share link of your ppt here so that I can close this issue.

Thanks

**Comment by thombrem** [comment]
[PyData_talk_intelligent_HR_chatbot.pptx](https://github.com/PyDataPune/Talks/files/2966882/PyData_talk_intelligent_HR_chatbot.pptx)

**Comment by thombrem** [comment]
[PyData_talk_intelligent_HR_chatbot.pptx](https://github.com/PyDataPune/Talks/files/2969795/PyData_talk_intelligent_HR_chatbot.pptx)

Please ignore the earlier slide deck

**Comment by PyDataPune** [comment]
Please go through the following readme to get an available screen recorder for your OS:

https://github.com/sigmakappa/ScreenRecorders
