### ISSUE TITLE
A Primer on Language Modelling

### ISSUE THREAD

**Issue by shaksham95** [PyDataPune/Talks#40]
**Title of the talk**
Advancements in Language Modelling

**Description**
In this talk, we will take a look into the recent acceleration in building NLP systems which were enabled by a shift of paradigm: for a long time, we used pre-trained word embeddings such as word2vec or GloVe which are now being "replaced" by advanced language models like ELMO, BERT, etc. 

**Topics to be covered:**

- Drawbacks of traditional word embeddings?

- A high-level overview of how ELMO address these issues

-  Shortcomings of ELMO, followed by deep dive into BERT

-  Different variants of BERT and current trends

**Prerequisites**
Basic familiarity with NLP and DL is good to have.

**Duration**
The session will be around 60-75 minutes (including QA) ❤️

**Comment by mayankskb** [comment]
Hi Shaksham,

Thanks for the talk proposal. We will use this issue for further communication related to the talk.

Thanks
Mayank Mishra

**Comment by shaksham95** [comment]
Thanks, Mayank. I have on request, it would be helpful if you can arrange for a whiteboard and markers. We might be needing them for explaining some concepts.

**Comment by mayankskb** [comment]
Hi Shaksham,

Thanks for informing about the logistics. We will take care of that.
Confirming your talk for Dec 14, 2019. 

Thanks
Mayank Mishra

**Comment by mayankskb** [comment]
Hi,

Please send a small write-up about you for introducing you. 

We will be recording your session. So if you have slides/demo/paper. Kindly keep it handy.

Also, you need to install screen recording software which can capture the presentation on your laptop. 

If you have any other alternate go with that if not then please go through the following readme to get an available screen recorder for your OS: https://github.com/sigmakappa/ScreenRecorders

Let me know if a screen recorder for your OS is not available here. Also, after installing do testing of it that it is working properly or not. Also, please give confirmation, once done with screen recorder testing stuff.

Thanks
Mayank Mishra

**Comment by shaksham95** [comment]
Hello Mayank,

I have been playing around with ShareX (OS: Windows) and it seems to work fine. It's capturing the entire screen, do we also need to capture audio?

Thanks
Shaksham

**Comment by mayankskb** [comment]
Cool! Audio we will capture

**Comment by mayankskb** [comment]
Shaksham please send a small write-up about you for introducing you.

**Comment by shaksham95** [comment]
Sure, Myanak. I will share that.

**Comment by shaksham95** [comment]
Hello Mayank,

Please find my introduction below;

Shaksham has over two years of experience in data science with his major focus on developing NLP based products. He is an experienced ML and NLP practitioner and is currently working as a Junior Data Scientist at Persistent Systems. He is also an independent researcher and has been researching and publishing papers in ML and NLP.

Apart from the professional front, he is a mentor/freelancer and has mentored/helped dozen of students and professionals and helped them kickstart their careers in data science.

On the personal side, he enjoys reading/listening to scientific podcats/books and loves playing Counter-Strike - Global Offensive.

**Comment by mayankskb** [comment]
Hi Shaksham,

Thanks for the wonderful talk. About the feedbacks from people, mostly the rating is 4 and 5 out of 5. This clearly signifies that people liked your talk.

About the screen recording, please upload it here: https://drive.google.com/drive/folders/1j9pPfLpSkA7el3cuhGhU_aY9SIXeLbRK?usp=sharing

Thanks
Mayank Mishra

**Comment by mayankskb** [comment]
Please let me know after uploading the video so that I can close this issue. 

Thanks
Mayank

**Comment by shaksham95** [comment]
Hey Mayank,

Sorry about the recording. I have checked my ShareX recordings and the session was not recorded. there is a 2-minute recording but it's not useful. We did start the recording before the session started but I am not sure why it didn't get recorded. Do you want me to record the presentations and share them with you? Or do you have any other ideas?

Thanks
Shaksham

**Comment by mayankskb** [comment]
Hi,

One possible alternate about which I can think of is on the basis of your recording, you need to record the screen matching the time on which you were saying something in the video and the content on the screen.

**Comment by shaksham95** [comment]
Yes, that sounds good. I can try that. From where can I access the recording?

**Comment by mayankskb** [comment]
Give me some time. I will notify you brother.

**Comment by mayankskb** [comment]
Hi Shaksham,

You can now check for your video recording in the same folder that I have shared above. Please have a look and upload screen recording in the same folder with name like "Shaksham - Language Modeling screen recording"

**Comment by shaksham95** [comment]
Sure Mayank, I will take a look at it and will try to record the presentation accordingly.

**Comment by shaksham95** [comment]
Hello Mayank,

I have recorded and uploaded the shareX recording for my session on the drive which you have shared. Please check that out and do let me know when the final video is out :)

Thanks
Shaksham

**Comment by mayankskb** [comment]
Hello Shaksham,

Thanks for sharing the screen recording for the presentation. I will notify you after the completion of the final video.

It would take some time.

Thanks
Mayank Mishra

**Comment by mayankskb** [comment]
Closing this issue as the purpose is completed for this one. Feel free to make new talk proposals.
