### ISSUE TITLE
Text Vectorization

### ISSUE THREAD

**Issue by KrishnaPriya401** [PyDataPune/Talks#41]
**Title of the talk**
Introduction to word embeddings

**Description**
In this talk, we will cover the following:-

- Statistical methods of converting text into a numeric representation.

-  The shortcoming of stats based methods and the advent of word embedding.

- Why do we need word representations? What is the "meaning" of a certain word? and how that meaning is encoded in numeric representations?

- Distributional Semantics

- Word2vec architecture in detail

**Prerequisites**
Basic familiarity with deep learning and NLP is good to have.

**Duration**
The session will be approx 60 minutes (including QA) ❤️

**Comment by mayankskb** [comment]
Hi KrishnaPriya,

Thanks for the talk proposal. We will use this issue for further communication related to the talk.

Thanks
Mayank Mishra

**Comment by KrishnaPriya401** [comment]
Thank you, Mayank.

**Comment by mayankskb** [comment]
Hi KrishnaPriya,

Finalizing your talk for Dec 14, 2019. 

Thanks 
Mayank Mishra

**Comment by mayankskb** [comment]
Hi,

Please send a small write-up about you for introducing you. 

We will be recording your session. So if you have slides/demo/paper. Kindly keep it handy.

Also, you need to install screen recording software which can capture the presentation on your laptop. 

If you have any other alternate go with that if not then please go through the following readme to get an available screen recorder for your OS: https://github.com/sigmakappa/ScreenRecorders

Let me know if a screen recorder for your OS is not available here. Also, after installing do testing of it that it is working properly or not. Also, please give confirmation, once done with screen recorder testing stuff.

Thanks
Mayank Mishra

**Comment by KrishnaPriya401** [comment]
Dear Mayank,

Thank you so much
I will surely do the needful and let you know.

Regards,
Krishna Priya

**Comment by mayankskb** [comment]
KrishnaPriya please send a small write-up about you for introducing you.

**Comment by KrishnaPriya401** [comment]
Hi  Mayank,
Here is my introduction

"
Krishna has got over three years’ worth of experience in data science where
her core focus was researching and developing NLP based products like
conversational interfaces. She is an ex-Senior Data Scientist with Kritrim
Inc (US-based, AI product development company) and helped them develop NLU
based products. Prior to joining Kritirm, she was in academics and has
worked as an Assitant Professor at Sinhgad Institue.
Currently, she is pursuing her Ph.D. in NLP where her primary focus is
using graph-based solutions to do opinion/sentiment mining and has
published several papers on data mining, machine learning, and NLP.

"

Thanks and regards, Krishna Priya

**Comment by mayankskb** [comment]
Hi KrishnaPriya,

Thanks for the wonderful talk. About the feedbacks from people, mostly the rating is 4 and 5 out of 5. This clearly signifies that people liked your talk.

About the screen recording, please upload it here: https://drive.google.com/drive/folders/1j9pPfLpSkA7el3cuhGhU_aY9SIXeLbRK?usp=sharing

Thanks
Mayank Mishra

**Comment by mayankskb** [comment]
Please let me know after uploading the video so that I can close this issue. Moreover, Krishna if you can help me with your email id or mob number so that I can approach you next time. You can send me text on 8380810361.


Thanks

**Comment by mayankskb** [comment]
Thanks!! Closing this issue. feel free to make new talk proposals. will schedule only after taking your consent
