### ISSUE TITLE
Lightning Talk:  Machine Learning for offensive security

### ISSUE THREAD

**Issue by adversarial-nik** [PyDataPune/Talks#43]
A brief look at applications of Machine Learning in offensive security. 
Following problems in offensive security are eagerly waiting for you **Deep learning researchers** to find out some interesting solutions. 
Via this talk I invite you all to learn more about these problems and also discuss the solutions that I have worked on.
 
We will discuss about: 

## Fuzzing
Fuzzing is a method of testing a target application by passing it unexpected set of data with an intention to identify security loopholes. ML can be used to generate input data for target software.

## Phishing
It needs no definition. Mails from SOC teams and IT admins are frustrating enough make everyone aware of Phishing attacks. ML can be used to automate targeted Phishing attacks and obtain higher success rate.

## Dictionary Attacks
A set of most commonly used passwords are used by some tools to crack the passwords. ML can be used to create a target specific Dictionary to make this attack effective.

**Comment by mayankskb** [comment]
Accepted for Jan 18, 2020.

**Comment by mayankskb** [comment]
Hi,

We will be recording your session. So if you have slides/demo/paper. Kindly keep it handy.

Also, you need to install a screen recording software that can capture the presentation on your laptop.

If you have any other alternate go with that if not then please go through the following readme to get an available screen recorder for your OS:

https://github.com/sigmakappa/ScreenRecorders

Let me know if a screen recorder for your OS is not available here. Also, after installing do testing of it that it is working properly or not. Also, please give confirmation, once done with screen recorder testing stuff.

Thanks
Mayank Mishra

**Comment by mayankskb** [comment]
Hi Nikhil,

Do send me a small writeup about you. We will use that for introducing you.

Thanks
Mayank Mishra

**Comment by adversarial-nik** [comment]
Hey Mayank,

Screen recording software installed and tested.

**Comment by mayankskb** [comment]
Hi Nikhil,

I would suggest you to upload your slide deck on speakerdeck and please share the link of that with me.

Thanks
Mayank Mishra

**Comment by PyDataPune** [comment]
Hi Nikhil,

Thanks for the meticulous lightning talk. Indeed we would live to conduct your full talk very soon. 
Meanwhile, if you want to propose more talks, feel free to do so.

Thanks
Admin @ PyData Pune
