### ISSUE TITLE
User Modeling: Recommendation Systems

### ISSUE THREAD

**Issue by aditya-malte** [PyDataPune/Talks#45]
## Overview
This talk will be giving a brief overview on various user modeling techniques, which will then be followed by discussing Recommendation Systems in depth.
## User Modeling(5-10 mins overview):
It is an important subdomain of data mining that is concerned with analyzing and predicting user behavior. Employed by Amazon, Twitter, Facebook, etc. to analyze their user/social media traffic.

This talk will give a brief overview of User Modeling with a more in-depth discussion on recommendation systems

## Example use cases include:
1. Collaborative Recommendation systems (this we all have heard of)
2. Context-Based Recommendation systems
3. Churn Modeling (predicting if XYZ user will leave the platform)
4. Graph link prediction (for eg. Facebook recommending other users for friend requests)
5. Anomaly Detection / Fraud
6. Other use cases like User Embedding (much like word embeddings)

## Recommendation Systems (40 mins)
We’ll discuss various use cases of different recommendation systems followed by an in detail study of algorithms in Implicit Recommendation Systems and a real-world use case/demo.

## Timeframe: 
Around 45-50 mins

## Props: 
Whiteboard, Projector/LCD, etc.

**Comment by mayankskb** [comment]
Hi Aditya,

We had a discussion over phone calls and messages regarding doubts related to the talk proposal and now it seems satisfactory to me.

Please consider this message as the acceptance for the talk for Feb 22, 2020.

Thanks
Mayank Mishra

**Comment by aditya-malte** [comment]
Thank you

**Comment by mayankskb** [comment]
Hi,

Please send a small write-up about you for introducing you.

We will be recording your session. So if you have slides/demo/paper. Kindly keep it handy.

Also, you need to install a screen recording software that can capture the presentation on your laptop.

If you have any other alternate go with that if not then please go through the following readme to get an available screen recorder for your OS: https://github.com/sigmakappa/ScreenRecorders

Let me know if a screen recorder for your OS is not available here. Also, after installing do testing of it that it is working properly or not. Also, please give confirmation, once done with screen recorder testing stuff.

Thanks
Mayank Mishra

**Comment by mayankskb** [comment]
Link to access photographs
https://photos.app.goo.gl/oYJHVZNfFp6Juy558

**Comment by mayankskb** [comment]
Hi Aditya,
Thanks for the talk. Closing this issue. Fell free to make new talk proposals.

Regards,
Mayank Mishra

**Comment by aditya-malte** [comment]
Thanks @mayankskb , it was a pleasure attending and delivering a talk at PyData
