### ISSUE TITLE
A 100 Databases (the world outside relational)

### ISSUE THREAD

**Issue by uday-dna** [PyDataPune/Talks#47]
### Overview

Did you know there are over 500 different databases in existence today? They are over a dozen types that are prevalent in the market. Relational, OLAP, Document are just the most common ones. However, there are many others out there that are transforming operational landscapes. Avenues that were once ignored or unexplored, are becoming differentiators for transformation. Our Analytical landscapes are not left out as well. Join this compelling Tech Talk to raise your awareness on the who's who of this new world of databases!

### Agenda:

1. The need to explore
2. What technology breakthroughs
3. The major types

- Relational
- OLAP
- Columnar
- Graph
- Timeseries
- NewSQL / Translytical
- Data Virtualization

4. A look at the most special ones

- MarkLogic
- SAP S/4HANA
- Presto
- Denodo
- Snowflake
- Elastic Search
- InfluxDB
- Neo4j
- AWS Databases Suite

4. Take away

### Pre-requisites:
Knowledge of any relational (SQL) database

### Duration

1 hour

**Comment by mayankskb** [comment]
Hi Uday!!

Thanks for submitting the talk proposal. Accepting it for Feb 22, 2020, as Host Talk. 

Thanks
Mayank Mishra

**Comment by mayankskb** [comment]
Hi,

Please send a small write-up about you for introducing you.

We will be recording your session. So if you have slides/demo/paper. Kindly keep it handy.

Also, you need to install a screen recording software that can capture the presentation on your laptop.

If you have any other alternate go with that if not then please go through the following readme to get an available screen recorder for your OS: https://github.com/sigmakappa/ScreenRecorders

Let me know if a screen recorder for your OS is not available here. Also, after installing do testing of it that it is working properly or not. Also, please give confirmation, once done with screen recorder testing stuff.

Thanks
Mayank Mishra

**Comment by uday-dna** [comment]
Hi Mayank,
I have setup Share X on my laptop. Also mailed you my intro write up.

Thanks,
Uday

**Comment by chessmastr** [comment]
Hi Uday,
It was really a nice session, very informative.
Please share the ppt here or personally.

**Comment by mayankskb** [comment]
Link to access photographs
https://photos.app.goo.gl/oYJHVZNfFp6Juy558

**Comment by mayankskb** [comment]
Thanks, Uday for the wonderful talk and recordings.. We will process them asap and will let you know once done. Closing this issue as the purpose is served.
Feel free to make new issues whenever you want to deliver talk. We will see where we can fit them according to theme.

Thanks
Mayank Mishra
