### ISSUE TITLE
Excursion to Neural Network

### ISSUE THREAD

**Issue by mayankskb** [PyDataPune/Talks#6]
The proposed Line Up
- What is Neural Network?
- Why we need Neural Network?
- Traditional ML vs Neural ML
- Inspiration behind Neural Network
- Anatomy of Neural Network
- Types of Neurons
- Components of Neural Networks
- Back propagation
- Importance of Non-linearity
- Types of Activation Functions 
- Initialization of weights and choosing optimizer
- Building your first Neural Network using Numpy
- Introduction to DL Frameworks (Which frameworks are available in market)
- Building you first NN using DL Framework
- What Next???

**Comment by PyDataPune** [comment]
Delivered!!
