### ISSUE TITLE
Visual Interpretability for convolutional neural networks

### ISSUE THREAD

**Issue by himanshurawlani** [PyDataPune/Talks#8]
In application programming, we have debugging and error checking statements like print, assert, try-catch, etc. But when it comes to deep neural networks, debugging becomes a bit tricky. Visualizing ConvNets gives us good intuition about the world of neural networks. This talk will be based on my blog post: [https://towardsdatascience.com/visual-interpretability-for-convolutional-neural-networks-2453856210ce](url)

The post discusses 4 important visualization techniques in convolutional neural network:
1. What is the output after each convolutional operation (Visualizing intermediate activations)
2. What features does each filter extract from the input image (Visualizing filters/kernels)
3. How to trace back output of each convolutional layer back to the input image (Visualizing using deconvnets a.k.a. deconvolutions/transposed convolutions)
4. Visualizing areas of interest, in the input image, for each layer of convnet (Visualizing heatmaps)

For each visualization technique, I plan to structure my talk in the following format:
1. Demonstrating a visualization technique
2. Interpreting the visualizations
3. Walkthrough of the code for the demonstrated visualization

The goal of this talk will be to give the audience an intuitive understanding of what CNNs learn and why given a particular dataset. Also, the talk aims to help encourage enthusiasts to dive into CNN architectures for better-debugging skills and improved explainability.

Also, if the audience request for a quick session on the basics of Convolutional Neural Networks then I plan to cover that. Since these basics are a must for understanding the visualization techniques.

**Comment by mayankskb** [comment]
Hey Himanshu,

Thanks for making an issue. Presenting apologies for a delayed response. We would like to have your talk for July PyData Meetup. Will let you know about the dates shortly.

Keep your stuff ready.
Thanks 
Mayank Mishra

**Comment by PyDataPune** [comment]
Hey,
DO let us know your availability for July,

**Comment by himanshurawlani** [comment]
Hi PyData Pune Team,

Currently I have no plans for July. But I'll confirm my availability by next week. Do let me know what dates are you planning.

**Comment by PyDataPune** [comment]
I hope you are good to go for July meetup. Do let us know about that?

**Comment by mayankskb** [comment]
Hey Himanshu,

We are setting July event themed on CNNs. Do let me know your availability for July 27, 2019.

Thanks
Mayank Mishra

**Comment by himanshurawlani** [comment]
Hi Mayank,

That sounds great! I'll make myself available on 27th July, 2019.

Thanks,
Himanshu Rawlani.

**Comment by mayankskb** [comment]
Hey,

We will be recording your session. So if you have slides/demo/paper. Kindly keep it handy.

Also, you need to install screen recording software which can capture the presentation on your laptop.

If you have any other alternate go with that if not then please go through the following readme to get an available screen recorder for your OS:

https://github.com/sigmakappa/ScreenRecorders

Let me know if a screen recorder for your OS is not available here.

Also, after installing do testing of it that it is working properly or not. 

Thanks 
Mayank Mishra

**Comment by mayankskb** [comment]
Hey Himanshu,

Please send us a small writeup about you.

Thanks 
Mayank Mishra

**Comment by mayankskb** [comment]
Hey Himanshu, 

Kindly upload your screen recording here: https://drive.google.com/drive/folders/1_az_VJ5sNWfKFdtcRqCfBnucrC_MVmBR?usp=sharing

Let me know in case of issues related to access for the folder.

Thanks
Mayank Mishra

**Comment by mayankskb** [comment]
Thank you for uploading the screen recording. We will process it as soon as possible and will share the link with you.

**Comment by mayankskb** [comment]
For now, closing this issue. Feel free to make a new issue for any new talk proposal.
