### ISSUE TITLE
Decision Optimization and Machine Learning

### ISSUE THREAD

**Issue by priyanka-kasture** [PyDataPune/Talks#9]
Decision Optimization + Machine Learning = Innovative solutions

The interplay between Decision Optimization and Machine learning is best appreciated when one understands how each technique complements the other. Machine Learning models bring the ability to provide accurate forecasts (demand forecasts, equipment failure predictions, etc.) by considering real-time inputs as well as historical data. While a reliable forecast is invaluable, having the ability to make analytics-driven decisions around the best course of action to take is priceless. This can be accomplished by feeding the forecasts generated by machine-learning models as inputs to a Decision Optimization model that can then consider the various tradeoffs and constraints to recommend the optimal solution to meet business goals.

On the other hand, once an optimization model has recommended an action plan and that plan is in operation, the data on the execution of that plan can be used by machine-learning models to improve forecasts, to automatically make the decision models more accurate, and to hedge against risks.

In the proposed talk I will make sure that the audience can learn the differences and complementary strengths of these two techniques, learn best practices, and see examples of combining these technologies to achieve gains and efficiencies.

**Comment by mayankskb** [comment]
Hey Priyanka,

Thanks for making an issue. It seems interesting to me. How much time you will need to prepare the content.

Thanks 
Mayank Mishra

**Comment by priyanka-kasture** [comment]
Thank you for considering my proposal.

4-5 days of preparation would be more than enough.

**Comment by PyDataPune** [comment]
Hey,

Let me know if you are available for May 24/25. If yes we can schedule your talk for May's PyData Pune Gang Up Event.

Thanks
Admin @ PyData Pune

**Comment by priyanka-kasture** [comment]
I'm available on, May 25. I have my exam on May 24.

Thanks!

**Comment by PyDataPune** [comment]
Ok Lemme see what date we will get finalised then will get back to you

**Comment by PyDataPune** [comment]
cool May 25 is Saturday. My bad should ask for 25/26. But not a problem 25 is super-awesome.

Prepare your content design the flow and please let us know.

**Comment by priyanka-kasture** [comment]
Sure! I'll send you all the details in about 3 days. :)

**Comment by mayankskb** [comment]
Hey Priyanka, 

We are waiting for the details

Thanks

**Comment by mayankskb** [comment]
Just a Quick reminder. Do Provide us the topics about which you are going to talk and the flow for the same.

**Comment by priyanka-kasture** [comment]
Hello Mayank,

The flow would be:

Introduction to optimization.
The need of optimization in artificial intelligence.
Optimization algorithms.
- Types.
-- Physics based.
-- Biology based.
-- Geography based.
- Loss functions.
- First order algorithms.
- Second order algorithms.
- Miscellaneous.
Current research trends.
Applications.

Thank you.

**Comment by mayankskb** [comment]
Hey, 

Thanks!! Finalizing your talk for May 25, 2019. Please make your slides and content. 
@sigmakappa Kindly mention the details regarding the screen recording. 

Thanks

**Comment by sigmakappa** [comment]
Screen recorder details here: https://github.com/sigmakappa/ScreenRecorders

**Comment by mayankskb** [comment]
Hey Priyanka,

Just FYI, We've postponed the meetup for 25 May. Will keep you posted about the updates.

Thanks
Mayank Mishra

**Comment by priyanka-kasture** [comment]
Sure Mayank. Thanks for informing.

**Comment by mayankskb** [comment]
Hey,

We are back with the dates. Your talk is already accepted here I am looking for your availability for June 22, 2019. If available then we are going to add it for June event.

Do let us know asap.

Thanks 
Mayank Mishra

**Comment by priyanka-kasture** [comment]
Thank you for the update, Mayank. I confirm my availability on the morning
of 22nd of June, 2019; from 10am - 12:30pm, at the maximum.

**Comment by mayankskb** [comment]
Cool!! There I am adding your talk on the list.


Please finalize your talk. 

CONFIRMED for June 22, 2019.

Thanks
Mayank Mishra

**Comment by mayankskb** [comment]
Hey,

Once you finalized your content do let me know the length of the talk.

**Comment by PyDataPune** [comment]
Hi here. Apologies for being a bit late in replying in suggesting a screen video recorder. Please go through the following readme to get an available screen recorder for your OS:

https://github.com/sigmakappa/ScreenRecorders

Let me know if a screen recorder for your OS is not available here.

**Comment by PyDataPune** [comment]
Thanks for delivering a talk at PyData Pune!!
